spring:
  application:
    name: smart-order-be-order-management-domain

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/midterm-domain2
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      minimum-idle: 2
      initialization-fail-timeout: 0
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      pool-name: OrderDomainHikariCP

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:      
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    open-in-view: false

  # SQL Init Configuration
  sql:
    init:
      mode: never
      

# Server Configuration
server:
  port: 8082
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024

# Logging Configuration
logging:
  level:
    root: INFO
    com.smartorder: DEBUG
    org.springframework.data: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management Endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# Custom Application Properties
app:
  order:
    max-items-per-order: 100
    auto-cancel-after-minutes: 30
    default-preparation-time: 15

  menu:
    cache-ttl-seconds: 3600
    max-items-per-category: 50

  billing:
    tax-rate: 0.1
    service-charge-rate: 0.05

